import { BigNumber } from "bignumber.js";

/**
 * Represents an ID that can be used to store records in the immutable data-store with strong
 * guarantees of k-ordering.
 */
export abstract class Id<T> {
  /**
   * A long value representing an ID as generated by the IdGenerator.
   */
  private id: T;

  /**
   * The timestamp this ID was created at, in milliseconds.
   */
  private time: number;

  public constructor(id: T, time: number) {
    this.id = id;
    this.time = time;
  }

  public getId(): T {
    return this.id;
  }

  public getTime(): number {
    return this.time;
  }

  public abstract toString(): string;
}